version: '3'
services:
  database:
    image: 'mongo:4.0.5'
    container_name: 'mongo-container'
    environment:
        - MONGO_INITDB_DATABASE=bank
        - MONGO_INITDB_ROOT_USERNAME=robert
        - MONGO_INITDB_ROOT_PASSWORD=robert
    volumes:
        - ./mongo-db/home/mongodb:/home/mongodb
        - ./mongo-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./mongo-db/mongo-data:/data/db
    ports:
        - '27017:27017'
        - '27018:27018'
        - '27019:27019'